### PR TITLE
Fix eventchanges 7.0.3

### PR DESCRIPTION
**Pull request by rdw-software**
Found this randomly on MMOC - easy fix, so I figured I'd let you know :)

### CODE REVIEW

**Comment by meribold** [comment]
Looks good, thanks! I'm currently not subscribed but if everything works in the current WoW patch with these changes I'll push a new release to Curse. If you're interested I can also make you the maintainer.

**Comment by rdw-software** [comment]
I haven't done much testing, but everything seemed fine. A user asked for help to fix it not recognizing the combo point updates since Legion hit, which is no longer an issue after applying this patch, but that appears to be the only problem they had - [link](http://www.mmo-champion.com/threads/2301418-Help-Editting-LUA-file-for-a-Simple-Combo-Point-Addon).

The addon seems simple enough. If somebody has an issue with it I can probably fix it without sacrificing too much of my time... so, yeah, I guess I can do that. This is my Curse account: [Profile](https://mods.curse.com/members/Cakechart)

**Comment by meribold** [comment]
It really was just an ad hoc addon for my UI but used to have some interesting heuristics to display combo points faster than the default UI (for Feral Druids) and without requiring a target, which is why I made it available separately. All of that was made obsolete with WoD, though (75403e5), and what's left is just the bare minimum that can be considered a combo point monitor.

**Comment by meribold** [comment]
You should be able to make commits to this repository as well now. Don't feel obliged to fix the addon if Blizzard makes any breaking changes.

**Comment by meribold** [comment]
I'll just upload a new release to Curse manually for now (I never looked into automating this).

**Comment by rdw-software** [comment]
[Automatic Packaging @ CurseForge](https://www.curseforge.com/docs/packaging)

**Pull request merged**
